### ISSUE TITLE
Email signup link opens landing page instead of Netlify backend on Safari

### ISSUE THREAD

**Issue by moritzsalla** [netlify/netlify-identity-widget#372]
There is no way to properly sign up if Safari is set as the standard browser. Copying the link URL and pasting it into Firefox or Chrome will trigger the signup interface.

**To Reproduce**
1. Add email address to netlify identity tab
2. Upon receiving the signup email, click the "Accept the invite" link
3. If Safari is set as the standard browser, the signup interface won't open, and the page index will appear

**Expected behavior**
When clicking the "accept the invite link", the "complete signup process" interface should appear in Safari.

**Applicable Versions:**
 - Netlify CMS version: 2.12.19
 - Git provider: Github
 - OS: MacOS 10.15.6
 - Browser version: Safari 14.0

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

…
```
